---
- name: Test | Get Service Status
  ansible.builtin.systemd_service:
    name: "{{ item }}"
  check_mode: true
  register: svc_status

- name: Test | Check Service - {{ item }}
  ansible.builtin.assert:
    that:
      - svc_status.status.ActiveState == "active"
    quiet: true
