---
- name: Test CA Server
  hosts: ca_server
  gather_facts: false
  tasks:
    - name: Provisioners Test | Get step-ca Configuration
      ansible.builtin.slurp:
        src: "/etc/step-ca/config/ca.json"
      register: ca_config

    - name: Provisioners Test | Get Provisioners From step-ca Config
      ansible.builtin.set_fact:
        provisioners: "{{ ca_config['content'] | b64decode | from_json | json_query(jmesquery) }}"
      vars:
        jmesquery: "authority.provisioners[*].type"

    - name: Provisioners Test | Check That ACME and OIDC Are Added to Provisioners
      ansible.builtin.assert:
        that:
          - provisioners == ["JWK", "SSHPOP", "ACME", "OIDC", "X5C"]

    - name: SSH Certificate Test | Check for Files
      ansible.builtin.include_tasks: ../tasks/file-check.yml
      loop:
        - /etc/step-ca/certs/ssh_host_ca_key.pub
        - /etc/step-ca/certs/ssh_user_ca_key.pub

- name: Test Client
  hosts: ca_clients
  gather_facts: false
  tasks:
    - name: Check for systemd Timers
      ansible.builtin.include_tasks: ../tasks/service-check.yml
      loop:
        - cert-renewer@{{ inventory_hostname }}.timer
        - ssh-cert-renewer@ssh_host_ecdsa_key.timer

    - name: SSH Certificate Test | Check for Files
      ansible.builtin.include_tasks: ../tasks/file-check.yml
      loop:
        - /etc/step-ca/certs/ssh_user_key.pub
        - /etc/ssh/ssh_host_ecdsa_key-cert.pub
