---
- name: Initialize Hosts
  hosts: all
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
      delay: 4
      retries: 5

    - name: Install essential packages for HTTPS
      ansible.builtin.apt:
        name:
          - gnupg
          - ca-certificates
          - apt-transport-https
        state: present
      when: ansible_distribution == 'Debian'

- name: Deploy a test CA server
  ansible.builtin.import_playbook: ../../../playbooks/ca.yml
  vars:
    step_ca_version: "{{ lookup('env', 'STEP_CA_VERSION') }}"
    step_cli_version: "{{ lookup('env', 'STEP_CLI_VERSION') }}"
    target_ca: "{{ lookup('env', 'TARGET_CA') }}"
    step_ca_alt_fqdn: "alt-fqdn.local"
