---
- name: Renewal | Create service template for cert-renewer
  ansible.builtin.template:
    src: cert-renewer@.service.j2
    dest: /etc/systemd/system/cert-renewer@.service
    mode: "0644"

- name: Renewal | Create timer template for cert-renewer
  ansible.builtin.template:
    src: cert-renewer@.timer.j2
    dest: /etc/systemd/system/cert-renewer@.timer
    mode: "0644"

- name: Renewal | Enable cert-renewer
  ansible.builtin.systemd_service:
    name: "cert-renewer@{{ item.name }}.timer"
    daemon_reload: true
    enabled: true
    state: started
  loop: "{{ step_cert_list }}"
