---
- name: Setup Step CA Clients (User Machines)
  hosts: "{{ target | default('clients_users') }}"
  become: true
  gather_facts: true
  roles:
    - name: Install Step CLI
      role: trfore.smallstep.step_cli

    - name: Bootstrap Step CA Root Certificate
      role: trfore.smallstep.step_ca_cert
      vars:
        step_ca_fingerprint: "" # noqa: var-naming[no-role-prefix]
        step_ca_url: "https://ca.example.com" # noqa: var-naming[no-role-prefix]
