name: CI

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  sanity:
    uses: ansible/ansible-content-actions/.github/workflows/sanity.yaml@main
  test:
    needs:
      - sanity
    strategy:
      fail-fast: false
      matrix:
        distro:
          [
            centos8,
            centos9,
            debian10,
            debian11,
            debian12,
            ubuntu2004,
            ubuntu2204,
            ubuntu2404,
          ]
        experimental: [false]
        molecule_scenario: ["-s default", "-s step_ssh"]
    uses: trfore/ansible-role/.github/workflows/test_ansible.yml@main
    with:
      distro: ${{ matrix.distro }}
      experimental: ${{ matrix.experimental }}
      molecule_glob: "./extensions/molecule/*/molecule.yml"
      molecule_scenario: ${{ matrix.molecule_scenario }}
      requirements_file: "requirements/dev-requirements.txt"
  check:
    if: ${{ always() && (github.event_name != 'schedule') }}
    needs:
      - sanity
      - test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.sanity.result }}',
          '${{ needs.test.result }}',
          ]) == {'success'}"
