name: Collection Docsite (Push)
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_docs:
    permissions:
      contents: read
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@main
    with:
      collection-name: trfore.smallstep
      init-fail-on-error: true
      init-copyright: trfore.smallstep contributors
      init-project: trfore.smallstep
      init-title: trfore.smallstep
      squash-hierarchy: true
      init-extra-html-theme-options: |
        documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/branch/main/

  publish_gh_pages:
    permissions:
      contents: write
    needs: build_docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@main
    with:
      artifact-name: ${{ needs.build_docs.outputs.artifact-name }}
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
