name: Release Check
on:
  pull_request:
    paths:
      - "step.version"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        distro: [centos9, debian12, ubuntu2404]
        molecule_scenario: ["-s default", "-s step_ssh"]
    uses: ./.github/workflows/test.yml
    with:
      distro: ${{ matrix.distro }}
      molecule_glob: "./extensions/molecule/*/molecule.yml"
      molecule_scenario: ${{ matrix.molecule_scenario }}
      requirements_file: "requirements/dev-requirements.txt"
  check:
    if: ${{ always() && (github.event_name != 'schedule') }}
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.test.result }}',
          ]) == {'success'}"
